//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluidXml.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluidXml.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;accdeath&quot;,&quot;car1&quot;,&quot;N&quot;
        ///&quot;accdeathlimit&quot;,&quot;car1&quot;,&quot;2147483645&quot;
        ///&quot;accdeathpremium&quot;,&quot;car1&quot;,&quot;0&quot;
        ///&quot;accountnumber&quot;,&quot;pol0&quot;,&quot;ITC999&quot;
        ///&quot;acordindustryoccupation&quot;,&quot;pol0&quot;,&quot;&quot;
        ///&quot;acordindustryoccupation&quot;,&quot;drv1&quot;,&quot;&quot;
        ///&quot;acv&quot;,&quot;car1&quot;,&quot;0&quot;
        ///&quot;acvw&quot;,&quot;car1&quot;,&quot;0&quot;
        ///&quot;address1&quot;,&quot;pol0&quot;,&quot;15100 Ella Vlcd &quot;
        ///&quot;address1&quot;,&quot;pol0&quot;,&quot;15100 Ella Vlcd &quot;
        ///&quot;address1&quot;,&quot;drv1&quot;,&quot;15100 Ella Vlcd &quot;
        ///&quot;address2&quot;,&quot;pol0&quot;,&quot;1803&quot;
        ///&quot;address2&quot;,&quot;drv1&quot;,&quot;1803&quot;
        ///&quot;address2&quot;,&quot;pol0&quot;,&quot;Apt #1803&quot;
        ///&quot;addressvalidated&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;addresswebrecordid&quot;,&quot;adr0&quot;,&quot;-1&quot;
        ///&quot;addtlpiplimit1&quot; [rest of string wa....
        /// </summary>
        internal static string _519b497fPolicy {
            get {
                return ResourceManager.GetString("_519b497fPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///  &lt;SignonRq&gt;
        ///    &lt;SignonPswd&gt;
        ///      &lt;CustId&gt;
        ///        &lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///        &lt;CustLoginId&gt;ivanstest000&lt;/CustLoginId&gt;
        ///      &lt;/CustId&gt;
        ///      &lt;CustPswd&gt;
        ///        &lt;EncryptionTypeCd&gt;None&lt;/EncryptionTypeCd&gt;
        ///        &lt;Pswd&gt;ivanstest000&lt;/Pswd&gt;
        ///      &lt;/CustPswd&gt;
        ///    &lt;/SignonPswd&gt;
        ///    &lt;ClientDt&gt;2015-10-13T15:21:50&lt;/ClientDt&gt;
        ///    &lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///    &lt;ClientApp&gt;
        ///      &lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///      &lt;Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aggregateexpected {
            get {
                return ResourceManager.GetString("aggregateexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///  &lt;SignonRq&gt;
        ///    &lt;SignonPswd&gt;
        ///      &lt;CustId&gt;
        ///        &lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///        &lt;CustLoginId&gt;ivanstest000&lt;/CustLoginId&gt;
        ///      &lt;/CustId&gt;
        ///      &lt;CustPswd&gt;
        ///        &lt;EncryptionTypeCd&gt;None&lt;/EncryptionTypeCd&gt;
        ///        &lt;Pswd&gt;ivanstest000&lt;/Pswd&gt;
        ///      &lt;/CustPswd&gt;
        ///    &lt;/SignonPswd&gt;
        ///    &lt;ClientDt&gt;2015-10-13T15:21:50&lt;/ClientDt&gt;
        ///    &lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///    &lt;ClientApp&gt;
        ///      &lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///      &lt;Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aggregatetest {
            get {
                return ResourceManager.GetString("aggregatetest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;establishQuoteHome_Type&gt;
        ///  &lt;HomePolicyQuoteInqRq&gt;
        ///    &lt;RqUID&gt;fffba332-b304-4e80-9d78-e16f8dda3414&lt;/RqUID&gt;
        ///    &lt;TransactionRequestDt&gt;2016-04-19T15:57:36&lt;/TransactionRequestDt&gt;
        ///    &lt;CurCd&gt;USD&lt;/CurCd&gt;
        ///    &lt;Producer&gt;
        ///      &lt;ItemIdInfo&gt;
        ///        &lt;OtherIdentifier&gt;
        ///          &lt;OtherIdTypeCd&gt;com.nationwide_RACFID&lt;/OtherIdTypeCd&gt;
        ///          &lt;OtherId&gt;AXZ808&lt;/OtherId&gt;
        ///          &lt;com.nationwide_OtherPwd&gt;itctest9&lt;/com.nationwide_OtherPwd&gt;
        ///        &lt;/OtherIdentifier&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string alliedreqxml {
            get {
                return ResourceManager.GetString("alliedreqxml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///	&lt;SignonRq&gt;
        ///		&lt;SignonTransport&gt;
        ///			&lt;SignonRoleCd&gt;Agent&lt;/SignonRoleCd&gt;
        ///			&lt;CustId&gt;
        ///				&lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///				&lt;CustPermId&gt;GGrant@getitc.com&lt;/CustPermId&gt;
        ///			&lt;/CustId&gt;
        ///		&lt;/SignonTransport&gt;
        ///		&lt;ClientDt&gt;2016-04-22T20:31:15&lt;/ClientDt&gt;
        ///		&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///		&lt;ClientApp&gt;
        ///			&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///			&lt;Name&gt;ITC.Insurance.AspenLimitedRR.TX&lt;/Name&gt;
        ///			&lt;Version&gt;1.0.0.0&lt;/Version&gt;
        ///		&lt;/ClientApp&gt;
        ///		&lt;CustPswd&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspenExpected {
            get {
                return ResourceManager.GetString("AspenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ACORD&gt;&lt;SignonRs&gt;&lt;Status&gt;&lt;StatusCd&gt;0&lt;/StatusCd&gt;&lt;StatusDesc&gt;Success&lt;/StatusDesc&gt;&lt;/Status&gt;&lt;ClientDt&gt;2016-04-22T16:11:52.157-1:15&lt;/ClientDt&gt;&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;&lt;ClientApp&gt;&lt;Org&gt;Aspen Managing General Agency&lt;/Org&gt;&lt;Name&gt;Aspen Bridge&lt;/Name&gt;&lt;Version&gt;1.0&lt;/Version&gt;&lt;/ClientApp&gt;&lt;ServerDt&gt;2016-04-22T16:11:52.157-1:15&lt;/ServerDt&gt;&lt;Language&gt;EN-US&lt;/Language&gt;&lt;/SignonRs&gt;&lt;InsuranceSvcRs&gt;&lt;RqUID&gt;68356c29-03c5-4722-825f-72b789a9ad50&lt;/RqUID&gt;&lt;PersAutoPolicyQuoteInqRs&gt;&lt;RqUID&gt;68356c29-03c5-4722-825f-72b789a9ad50&lt;/RqUID&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspenResponse {
            get {
                return ResourceManager.GetString("AspenResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;ACORD&gt;&lt;SignonRq&gt;&lt;SignonPswd&gt;&lt;CustId&gt;&lt;SPName&gt;turborater.com&lt;/SPName&gt;&lt;CustLoginId&gt;NVDB Pricing&lt;/CustLoginId&gt;&lt;/CustId&gt;&lt;CustPswd&gt;&lt;EncryptionTypeCd&gt;None&lt;/EncryptionTypeCd&gt;&lt;Pswd&gt;Mar2016&lt;/Pswd&gt;&lt;/CustPswd&gt;&lt;/SignonPswd&gt;&lt;ClientDt&gt;2016-04-14T18:36:43&lt;/ClientDt&gt;&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;&lt;ClientApp&gt;&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;&lt;Name&gt;ITC.Insurance.AmericanAccessRR.NV&lt;/Name&gt;&lt;Version&gt;1.0.0.0&lt;/Version&gt;&lt;/ClientApp&gt;&lt;/SignonRq&gt;&lt;InsuranceSvcRq&gt;&lt;RqUID&gt;dc7fcc18-7369-4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desc1actual {
            get {
                return ResourceManager.GetString("desc1actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///	&lt;SignonRq&gt;
        ///		&lt;SignonPswd&gt;
        ///			&lt;CustId&gt;
        ///				&lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///				&lt;CustLoginId&gt;NVDB Pricing&lt;/CustLoginId&gt;
        ///			&lt;/CustId&gt;
        ///			&lt;CustPswd&gt;
        ///				&lt;EncryptionTypeCd&gt;None&lt;/EncryptionTypeCd&gt;
        ///				&lt;Pswd&gt;Mar2016&lt;/Pswd&gt;
        ///			&lt;/CustPswd&gt;
        ///		&lt;/SignonPswd&gt;
        ///		&lt;ClientDt&gt;2016-04-14T18:36:43&lt;/ClientDt&gt;
        ///		&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///		&lt;ClientApp&gt;
        ///			&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///			&lt;Name&gt;ITC.Insurance.AmericanAccessRR.NV&lt;/Name&gt;
        ///			&lt;Ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desc1expected {
            get {
                return ResourceManager.GetString("desc1expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;establishQuoteHome_Type xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; com.nationwide_PartnerId=&quot;TurboRater&quot; xmlns=&quot;http://nationwide.com/schemas/policyAcquisition/acord_PC_1_22/External/InsurancePolicyQuote_1&quot;&gt;
        ///  &lt;HomePolicyQuoteInqRq&gt;
        ///    &lt;RqUID&gt;0b7b612d-c8e0-486a-9fef-f1d5f05a31b3&lt;/RqUID&gt;
        ///    &lt;TransactionRequestDt&gt;2016-04-20T17:08:03&lt;/TransactionRequestDt&gt;
        ///    &lt;CurCd&gt;USD&lt;/CurCd&gt;
        ///    &lt;Producer&gt;
        ///      &lt;ItemI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desc2actual {
            get {
                return ResourceManager.GetString("desc2actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;establishQuoteHome_Type xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; com.nationwide_PartnerId=&quot;TurboRater&quot; xmlns=&quot;http://nationwide.com/schemas/policyAcquisition/acord_PC_1_22/External/InsurancePolicyQuote_1&quot;&gt;
        ///  &lt;HomePolicyQuoteInqRq&gt;
        ///    &lt;RqUID&gt;0b7b612d-c8e0-486a-9fef-f1d5f05a31b3&lt;/RqUID&gt;
        ///    &lt;TransactionRequestDt&gt;2016-04-20T17:08:03&lt;/TransactionRequestDt&gt;
        ///    &lt;CurCd&gt;USD&lt;/CurCd&gt;
        ///    &lt;Producer&gt;
        ///      &lt;ItemI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desc2expected {
            get {
                return ResourceManager.GetString("desc2expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///	&lt;SignonRq&gt;
        ///		&lt;SignonPswd&gt;
        ///			&lt;SignonRoleCd&gt;Agent&lt;/SignonRoleCd&gt;
        ///			&lt;CustId&gt;
        ///				&lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///				&lt;CustLoginId&gt;TITCWSP01&lt;/CustLoginId&gt;
        ///			&lt;/CustId&gt;
        ///			&lt;CustPswd&gt;
        ///				&lt;Pswd&gt;siz3.t1m3&lt;/Pswd&gt;
        ///				&lt;EncryptionTypeCd&gt;NONE&lt;/EncryptionTypeCd&gt;
        ///			&lt;/CustPswd&gt;
        ///		&lt;/SignonPswd&gt;
        ///		&lt;ClientDt&gt;2015-10-08T15:17:10&lt;/ClientDt&gt;
        ///		&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///		&lt;ClientApp&gt;
        ///			&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///			&lt;Name&gt;ITC.Insura [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desc3actual {
            get {
                return ResourceManager.GetString("desc3actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///	&lt;SignonRq&gt;
        ///		&lt;SignonPswd&gt;
        ///			&lt;SignonRoleCd&gt;Agent&lt;/SignonRoleCd&gt;
        ///			&lt;CustId&gt;
        ///				&lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///				&lt;CustLoginId&gt;TITCWSP01&lt;/CustLoginId&gt;
        ///			&lt;/CustId&gt;
        ///			&lt;CustPswd&gt;
        ///				&lt;Pswd&gt;siz3.t1m3&lt;/Pswd&gt;
        ///				&lt;EncryptionTypeCd&gt;NONE&lt;/EncryptionTypeCd&gt;
        ///			&lt;/CustPswd&gt;
        ///		&lt;/SignonPswd&gt;
        ///		&lt;ClientDt&gt;2015-10-08T15:17:10&lt;/ClientDt&gt;
        ///		&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///		&lt;ClientApp&gt;
        ///			&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///			&lt;Name&gt;ITC.Insura [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desc3expected {
            get {
                return ResourceManager.GetString("desc3expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///	&lt;SignonRq&gt;
        ///		&lt;SignonPswd&gt;
        ///			&lt;CustId&gt;
        ///				&lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///				&lt;CustLoginId&gt;NVDB Pricing&lt;/CustLoginId&gt;
        ///			&lt;/CustId&gt;
        ///			&lt;CustPswd&gt;
        ///				&lt;EncryptionTypeCd&gt;None&lt;/EncryptionTypeCd&gt;
        ///				&lt;Pswd&gt;Mar2016&lt;/Pswd&gt;
        ///			&lt;/CustPswd&gt;
        ///		&lt;/SignonPswd&gt;
        ///		&lt;ClientDt&gt;2016-04-14T18:36:43&lt;/ClientDt&gt;
        ///		&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///		&lt;ClientApp&gt;
        ///			&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///			&lt;Name&gt;ITC.Insurance.AmericanAccessRR.NV&lt;/Name&gt;
        ///			&lt;Ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desc4actual {
            get {
                return ResourceManager.GetString("desc4actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///	&lt;SignonRq&gt;
        ///		&lt;SignonPswd&gt;
        ///			&lt;CustId&gt;
        ///				&lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///				&lt;CustLoginId&gt;NVDB Pricing&lt;/CustLoginId&gt;
        ///			&lt;/CustId&gt;
        ///			&lt;CustPswd&gt;
        ///				&lt;EncryptionTypeCd&gt;None&lt;/EncryptionTypeCd&gt;
        ///				&lt;Pswd&gt;Mar2016&lt;/Pswd&gt;
        ///			&lt;/CustPswd&gt;
        ///		&lt;/SignonPswd&gt;
        ///		&lt;ClientDt&gt;2016-04-14T18:36:43&lt;/ClientDt&gt;
        ///		&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///		&lt;ClientApp&gt;
        ///			&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///			&lt;Name&gt;ITC.Insurance.AmericanAccessRR.NV&lt;/Name&gt;
        ///			&lt;Ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desc4expected {
            get {
                return ResourceManager.GetString("desc4expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;ACORD xmlns:com.hallmark=&quot;http://www.hallmarkgrp.com&quot;&gt;&lt;Status&gt;&lt;StatusCd&gt;0&lt;/StatusCd&gt;&lt;StatusDesc&gt;ACORD Success&lt;/StatusDesc&gt;&lt;/Status&gt;&lt;InsuranceSvcRs&gt;&lt;RqUID&gt;73777bb6-6e26-4dcf-8005-ca0784355d69&lt;/RqUID&gt;&lt;PersAutoPolicyQuoteInqRs&gt;&lt;MsgStatus&gt;&lt;MsgStatusCd&gt;Success&lt;/MsgStatusCd&gt;&lt;MsgStatusDesc&gt;Personal Auto Policy Success&lt;/MsgStatusDesc&gt;&lt;/MsgStatus&gt;&lt;RqUID&gt;73777bb6-6e26-4dcf-8005-ca0784355d69&lt;/RqUID&gt;&lt;TransactionRequestDt&gt;2016-04-11T13:03:05&lt;/TransactionRequestDt&gt;&lt;TransactionEffect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HallmarkResponse {
            get {
                return ResourceManager.GetString("HallmarkResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;nonowner&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;isoperator&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;broadform&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;sr22fee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;numofdrivers&quot;,&quot;pol0&quot;,&quot;1&quot;
        ///&quot;numofexclusions&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;numofcars&quot;,&quot;pol0&quot;,&quot;1&quot;
        ///&quot;fulltort&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;atpafee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;collectionfee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;lawenforcefee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;municipaltax&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;municipaltaxrate&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;securityverificationfee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;stampfee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;statetax&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;statetaxrate&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;tax&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;uninsmotorfe....
        /// </summary>
        internal static string Policy21b2c5fe {
            get {
                return ResourceManager.GetString("Policy21b2c5fe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;nonowner&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;isoperator&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;broadform&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;sr22fee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;numofdrivers&quot;,&quot;pol0&quot;,&quot;1&quot;
        ///&quot;numofexclusions&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;numofcars&quot;,&quot;pol0&quot;,&quot;2&quot;
        ///&quot;fulltort&quot;,&quot;pol0&quot;,&quot;N&quot;
        ///&quot;atpafee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;collectionfee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;lawenforcefee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;municipaltax&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;municipaltaxrate&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;securityverificationfee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;stampfee&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;statetax&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;statetaxrate&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;tax&quot;,&quot;pol0&quot;,&quot;0&quot;
        ///&quot;uninsmotorfe....
        /// </summary>
        internal static string TX_b74e03f8Policy {
            get {
                return ResourceManager.GetString("TX_b74e03f8Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///	&lt;SignonRq&gt;
        ///		&lt;SignonPswd&gt;
        ///			&lt;CustId&gt;
        ///				&lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///				&lt;CustLoginId&gt;ivanstest000&lt;/CustLoginId&gt;
        ///			&lt;/CustId&gt;
        ///			&lt;CustPswd&gt;
        ///				&lt;EncryptionTypeCd&gt;None&lt;/EncryptionTypeCd&gt;
        ///				&lt;Pswd&gt;ivanstest000&lt;/Pswd&gt;
        ///			&lt;/CustPswd&gt;
        ///		&lt;/SignonPswd&gt;
        ///		&lt;ClientDt&gt;2016-01-22T16:01:18&lt;/ClientDt&gt;
        ///		&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///		&lt;ClientApp&gt;
        ///			&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///			&lt;Name&gt;ITC.Insurance.HallmarkRR.AR&lt;/Name&gt;
        ///			&lt;Ver [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string updatenodeexpected {
            get {
                return ResourceManager.GetString("updatenodeexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ACORD&gt;
        ///	&lt;SignonRq&gt;
        ///		&lt;SignonPswd&gt;
        ///			&lt;CustId&gt;
        ///				&lt;SPName&gt;turborater.com&lt;/SPName&gt;
        ///				&lt;CustLoginId&gt;ivanstest000&lt;/CustLoginId&gt;
        ///			&lt;/CustId&gt;
        ///			&lt;CustPswd&gt;
        ///				&lt;EncryptionTypeCd&gt;None&lt;/EncryptionTypeCd&gt;
        ///				&lt;Pswd&gt;ivanstest000&lt;/Pswd&gt;
        ///			&lt;/CustPswd&gt;
        ///		&lt;/SignonPswd&gt;
        ///		&lt;ClientDt&gt;2016-01-22T16:01:18&lt;/ClientDt&gt;
        ///		&lt;CustLangPref&gt;EN-US&lt;/CustLangPref&gt;
        ///		&lt;ClientApp&gt;
        ///			&lt;Org&gt;Insurance Technologies Corporation&lt;/Org&gt;
        ///			&lt;Name&gt;ITC.Insurance.HallmarkRR.AR&lt;/Name&gt;
        ///			&lt;Ver [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string updatenodetest {
            get {
                return ResourceManager.GetString("updatenodetest", resourceCulture);
            }
        }
    }
}
